'use client';

import React, { useState } from 'react';
import { BlindSpotAuditResult } from '@/types/blindspot';
import {
  AlertTriangle,
  HelpCircle,
  Zap,
  Clock,
  Eye,
  CheckCircle2,
  Copy,
  RotateCcw,
  Sparkles,
  ArrowRight,
  ShieldCheck,
  Split,
  Layers,
  Search,
} from 'lucide-react';

interface ResultsDashboardProps {
  result: BlindSpotAuditResult;
  onReset: () => void;
}

export const ResultsDashboard: React.FC<ResultsDashboardProps> = ({ result, onReset }) => {
  const [activeTab, setActiveTab] = useState<'all' | 'assumptions' | 'missing' | 'conflicts' | 'secondOrder' | 'time' | 'perspectives' | 'evidence' | 'questions'>('all');
  const [copied, setCopied] = useState(false);

  const handleCopyReport = () => {
    const textReport = `BLINDSPOT REASONING AUDIT REPORT
====================================
CORE DECISION: ${result.decisionCore}

EXECUTIVE REASONING DIAGNOSTIC:
${result.summary}

CRITICAL BLIND SPOT:
${result.criticalBlindSpotHighlight}

1. ASSUMPTIONS DETECTED (${result.assumptions.length}):
${result.assumptions.map((a, i) => `  ${i + 1}. [${a.strength.toUpperCase()}] ${a.title}: ${a.description}\n     Why it matters: ${a.whyItMatters}`).join('\n\n')}

2. MISSING INFORMATION (${result.missingInformation.length}):
${result.missingInformation.map((m, i) => `  ${i + 1}. [${m.impact.toUpperCase()}] ${m.title}: ${m.description}\n     Action: ${m.howToAcquire || 'Verify with primary source'}`).join('\n\n')}

3. REASONING CONFLICTS (${result.reasoningConflicts.length}):
${result.reasoningConflicts.map((c, i) => `  ${i + 1}. ${c.title} (${c.tensionType}): ${c.description}\n     Reconciliation: ${c.reconciliationPrompt || ''}`).join('\n\n')}

4. SECOND-ORDER EFFECTS (${result.secondOrderEffects.length}):
${result.secondOrderEffects.map((s, i) => `  ${i + 1}. [${s.timeline}] ${s.title}: ${s.description}\n     Downstream: ${s.potentialDownsideOrOpportunity || ''}`).join('\n\n')}

5. TIME-HORIZON BIASES:
${result.timeHorizon.map((t, i) => `  ${i + 1}. ${t.title} (${t.biasType}): ${t.description}\n     Balancing question: ${t.balancingQuestion || ''}`).join('\n\n')}

6. HIGH-VALUE QUESTIONS:
${result.questions.map((q, i) => `  ${i + 1}. ${q.question} [${q.category}]\n     Why: ${q.whyItMatters}`).join('\n\n')}

Report generated by BlindSpot AI — Never tells you what to choose; audits how you choose.
`;

    navigator.clipboard.writeText(textReport);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const scrollToSection = (id: string, tab: typeof activeTab) => {
    setActiveTab(tab);
    if (tab !== 'all') {
      const el = document.getElementById(id);
      if (el) {
        el.scrollIntoView({ behavior: 'smooth' });
      }
    }
  };

  return (
    <div className="results-container">
      {/* Top Reasoning Diagnostic Banner */}
      <div className="diagnostic-banner">
        <div className="diagnostic-top">
          <div className="diagnostic-title-wrap">
            <span className="status-chip">
              <ShieldCheck size={14} />
              Reasoning Audit Complete
            </span>
          </div>

          <div className="toolbar-actions">
            <button type="button" className="btn-secondary" onClick={handleCopyReport}>
              {copied ? <CheckCircle2 size={14} color="#10b981" /> : <Copy size={14} />}
              <span>{copied ? 'Audit Copied!' : 'Copy Text Report'}</span>
            </button>
            <button type="button" className="btn-secondary" onClick={onReset}>
              <RotateCcw size={14} />
              <span>Start Another Analysis</span>
            </button>
          </div>
        </div>

        <div>
          <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.04em', marginBottom: '0.25rem' }}>
            Decision Under Audit
          </div>
          <div className="diagnostic-decision">{result.decisionCore}</div>
        </div>

        <div className="diagnostic-summary">
          <strong>Reasoning Snapshot: </strong>
          {result.summary}
        </div>

        {result.criticalBlindSpotHighlight && (
          <div className="critical-spot-alert">
            <AlertTriangle size={22} color="#f43f5e" style={{ flexShrink: 0, marginTop: '2px' }} />
            <div>
              <div className="critical-spot-title">Critical Blind Spot Identified</div>
              <div className="critical-spot-text">{result.criticalBlindSpotHighlight}</div>
            </div>
          </div>
        )}
      </div>

      {/* Sticky Navigation / Category Filters */}
      <div className="dashboard-nav-bar">
        <div className="nav-tabs">
          <button
            type="button"
            className={`nav-tab-btn ${activeTab === 'all' ? 'active' : ''}`}
            onClick={() => setActiveTab('all')}
          >
            All Findings
          </button>
          <button
            type="button"
            className={`nav-tab-btn ${activeTab === 'assumptions' ? 'active' : ''}`}
            onClick={() => scrollToSection('sec-assumptions', 'assumptions')}
          >
            Assumptions
            <span className="tab-badge">{result.assumptions.length}</span>
          </button>
          <button
            type="button"
            className={`nav-tab-btn ${activeTab === 'missing' ? 'active' : ''}`}
            onClick={() => scrollToSection('sec-missing', 'missing')}
          >
            Missing Info
            <span className="tab-badge">{result.missingInformation.length}</span>
          </button>
          <button
            type="button"
            className={`nav-tab-btn ${activeTab === 'conflicts' ? 'active' : ''}`}
            onClick={() => scrollToSection('sec-conflicts', 'conflicts')}
          >
            Conflicts
            <span className="tab-badge">{result.reasoningConflicts.length}</span>
          </button>
          <button
            type="button"
            className={`nav-tab-btn ${activeTab === 'secondOrder' ? 'active' : ''}`}
            onClick={() => scrollToSection('sec-second-order', 'secondOrder')}
          >
            2nd-Order Effects
            <span className="tab-badge">{result.secondOrderEffects.length}</span>
          </button>
          <button
            type="button"
            className={`nav-tab-btn ${activeTab === 'time' ? 'active' : ''}`}
            onClick={() => scrollToSection('sec-time', 'time')}
          >
            Time Horizon
            <span className="tab-badge">{result.timeHorizon.length}</span>
          </button>
          <button
            type="button"
            className={`nav-tab-btn ${activeTab === 'perspectives' ? 'active' : ''}`}
            onClick={() => scrollToSection('sec-perspectives', 'perspectives')}
          >
            Perspectives
            <span className="tab-badge">{result.perspectiveShifts.length}</span>
          </button>
          <button
            type="button"
            className={`nav-tab-btn ${activeTab === 'evidence' ? 'active' : ''}`}
            onClick={() => scrollToSection('sec-evidence', 'evidence')}
          >
            Evidence vs Belief
            <span className="tab-badge">{result.evidenceVsBelief.length}</span>
          </button>
          <button
            type="button"
            className={`nav-tab-btn ${activeTab === 'questions' ? 'active' : ''}`}
            onClick={() => scrollToSection('sec-questions', 'questions')}
          >
            Key Questions
            <span className="tab-badge">{result.questions.length}</span>
          </button>
        </div>
      </div>

      {/* SECTION 1: Assumptions Detected */}
      {(activeTab === 'all' || activeTab === 'assumptions') && (
        <section id="sec-assumptions" className="audit-section">
          <div className="section-header">
            <div className="section-title-wrap">
              <AlertTriangle className="section-icon" size={22} color="#f59e0b" />
              <div>
                <h2 className="section-title">Assumption Audit</h2>
                <p className="section-subtitle">
                  Premises taken for granted without empirical validation.
                </p>
              </div>
            </div>
            <span className="badge-tag">{result.assumptions.length} Identified</span>
          </div>

          {result.assumptions.length === 0 ? (
            <div style={{ color: 'var(--text-muted)', fontStyle: 'italic', padding: '1rem' }}>
              No critical unexamined assumptions detected in the stated reasoning.
            </div>
          ) : (
            <div className="cards-grid">
              {result.assumptions.map((item, idx) => (
                <div key={idx} className="finding-card">
                  <div className="finding-card-top">
                    <h3 className="finding-card-title">{item.title}</h3>
                    <span className={`severity-pill severity-${item.strength}`}>
                      {item.strength} impact
                    </span>
                  </div>

                  <p className="finding-description">{item.description}</p>

                  <div className="finding-meta-box">
                    <span className="meta-label">Why It Matters</span>
                    <span className="meta-value">{item.whyItMatters}</span>
                  </div>

                  {item.untestedPremise && (
                    <div style={{ fontSize: '0.8rem', color: '#94a3b8' }}>
                      <strong style={{ color: '#cbd5e1' }}>Untested premise:</strong>{' '}
                      {item.untestedPremise}
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </section>
      )}

      {/* SECTION 2: Missing Information */}
      {(activeTab === 'all' || activeTab === 'missing') && (
        <section id="sec-missing" className="audit-section">
          <div className="section-header">
            <div className="section-title-wrap">
              <Search className="section-icon" size={22} color="#06b6d4" />
              <div>
                <h2 className="section-title">Material Missing Information</h2>
                <p className="section-subtitle">
                  Vital data points absent from the description that could flip the decision.
                </p>
              </div>
            </div>
            <span className="badge-tag">{result.missingInformation.length} Identified</span>
          </div>

          {result.missingInformation.length === 0 ? (
            <div style={{ color: 'var(--text-muted)', fontStyle: 'italic', padding: '1rem' }}>
              No major information omissions detected based on the context provided.
            </div>
          ) : (
            <div className="cards-grid">
              {result.missingInformation.map((item, idx) => (
                <div key={idx} className="finding-card">
                  <div className="finding-card-top">
                    <h3 className="finding-card-title">{item.title}</h3>
                    <span className={`severity-pill severity-${item.impact}`}>
                      {item.impact} materiality
                    </span>
                  </div>

                  <p className="finding-description">{item.description}</p>

                  <div className="finding-meta-box" style={{ borderLeftColor: '#06b6d4' }}>
                    <span className="meta-label" style={{ color: '#67e8f9' }}>
                      Risk of Deciding Without This
                    </span>
                    <span className="meta-value">{item.whyItMatters}</span>
                  </div>

                  {item.howToAcquire && (
                    <div className="action-chip">
                      <ArrowRight size={13} />
                      <span>{item.howToAcquire}</span>
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </section>
      )}

      {/* SECTION 3: Reasoning Conflicts */}
      {(activeTab === 'all' || activeTab === 'conflicts') && (
        <section id="sec-conflicts" className="audit-section">
          <div className="section-header">
            <div className="section-title-wrap">
              <Split className="section-icon" size={22} color="#f43f5e" />
              <div>
                <h2 className="section-title">Reasoning Conflicts &amp; Tensions</h2>
                <p className="section-subtitle">
                  Contradictions between stated priorities and your chosen leaning.
                </p>
              </div>
            </div>
            <span className="badge-tag">{result.reasoningConflicts.length} Identified</span>
          </div>

          {result.reasoningConflicts.length === 0 ? (
            <div style={{ color: 'var(--text-muted)', fontStyle: 'italic', padding: '1rem' }}>
              No direct contradictions identified between stated priorities and reasoning logic.
            </div>
          ) : (
            <div className="cards-grid">
              {result.reasoningConflicts.map((item, idx) => (
                <div key={idx} className="finding-card" style={{ borderColor: 'rgba(244, 63, 94, 0.25)' }}>
                  <div className="finding-card-top">
                    <h3 className="finding-card-title">{item.title}</h3>
                    <span
                      className="severity-pill"
                      style={{ background: 'rgba(244, 63, 94, 0.12)', color: '#fb7185' }}
                    >
                      {item.tensionType}
                    </span>
                  </div>

                  <p className="finding-description">{item.description}</p>

                  <div className="finding-meta-box" style={{ borderLeftColor: '#f43f5e' }}>
                    <span className="meta-label" style={{ color: '#fda4af' }}>
                      Why This Friction Matters
                    </span>
                    <span className="meta-value">{item.whyItMatters}</span>
                  </div>

                  {item.reconciliationPrompt && (
                    <div style={{ background: 'rgba(255, 255, 255, 0.04)', borderRadius: '8px', padding: '0.75rem', fontSize: '0.85rem', color: '#e2e8f0' }}>
                      <strong style={{ color: '#f43f5e' }}>Reconciliation Prompt:</strong>{' '}
                      {item.reconciliationPrompt}
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </section>
      )}

      {/* SECTION 4: Second-Order Effects */}
      {(activeTab === 'all' || activeTab === 'secondOrder') && (
        <section id="sec-second-order" className="audit-section">
          <div className="section-header">
            <div className="section-title-wrap">
              <Layers className="section-icon" size={22} color="#8b5cf6" />
              <div>
                <h2 className="section-title">Second-Order Ripple Effects</h2>
                <p className="section-subtitle">
                  Consequences that occur downstream because of the decision.
                </p>
              </div>
            </div>
            <span className="badge-tag">{result.secondOrderEffects.length} Identified</span>
          </div>

          <div className="cards-grid">
            {result.secondOrderEffects.map((item, idx) => (
              <div key={idx} className="finding-card">
                <div className="finding-card-top">
                  <h3 className="finding-card-title">{item.title}</h3>
                  <span
                    className="severity-pill"
                    style={{ background: 'rgba(139, 92, 246, 0.15)', color: '#c4b5fd' }}
                  >
                    {item.timeline}
                  </span>
                </div>

                <p className="finding-description">{item.description}</p>

                <div className="finding-meta-box" style={{ borderLeftColor: '#8b5cf6' }}>
                  <span className="meta-label" style={{ color: '#c4b5fd' }}>
                    Ripple Consequence
                  </span>
                  <span className="meta-value">{item.whyItMatters}</span>
                </div>

                {item.potentialDownsideOrOpportunity && (
                  <div style={{ fontSize: '0.82rem', color: '#94a3b8' }}>
                    <strong style={{ color: '#cbd5e1' }}>Downstream effect:</strong>{' '}
                    {item.potentialDownsideOrOpportunity}
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>
      )}

      {/* SECTION 5: Time Horizon */}
      {(activeTab === 'all' || activeTab === 'time') && (
        <section id="sec-time" className="audit-section">
          <div className="section-header">
            <div className="section-title-wrap">
              <Clock className="section-icon" size={22} color="#06b6d4" />
              <div>
                <h2 className="section-title">Time-Horizon Considerations</h2>
                <p className="section-subtitle">
                  Present bias, immediate excitement vs delayed compounding impact.
                </p>
              </div>
            </div>
            <span className="badge-tag">{result.timeHorizon.length} Identified</span>
          </div>

          <div className="cards-grid">
            {result.timeHorizon.map((item, idx) => (
              <div key={idx} className="finding-card">
                <div className="finding-card-top">
                  <h3 className="finding-card-title">{item.title}</h3>
                  <span
                    className="severity-pill"
                    style={{ background: 'rgba(6, 182, 212, 0.12)', color: '#67e8f9' }}
                  >
                    {item.biasType}
                  </span>
                </div>

                <p className="finding-description">{item.description}</p>

                <div className="finding-meta-box" style={{ borderLeftColor: '#06b6d4' }}>
                  <span className="meta-label" style={{ color: '#67e8f9' }}>
                    Temporal Asymmetry
                  </span>
                  <span className="meta-value">{item.whyItMatters}</span>
                </div>

                {item.balancingQuestion && (
                  <div style={{ fontStyle: 'italic', fontSize: '0.85rem', color: '#cbd5e1' }}>
                    &ldquo;{item.balancingQuestion}&rdquo;
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>
      )}

      {/* SECTION 6: Perspective Shifts */}
      {(activeTab === 'all' || activeTab === 'perspectives') && (
        <section id="sec-perspectives" className="audit-section">
          <div className="section-header">
            <div className="section-title-wrap">
              <Eye className="section-icon" size={22} color="#8b5cf6" />
              <div>
                <h2 className="section-title">Alternative Perspective Shifts</h2>
                <p className="section-subtitle">
                  Viewing your decision through divergent stakeholder and observer lenses.
                </p>
              </div>
            </div>
            <span className="badge-tag">4 Cognitive Angles</span>
          </div>

          <div className="perspectives-grid">
            {result.perspectiveShifts.map((item, idx) => (
              <div key={idx} className="perspective-card">
                <div className="perspective-badge">
                  <span>{item.perspectiveLabel}</span>
                </div>

                <h3 style={{ fontSize: '1.05rem', fontWeight: 700, color: '#f8fafc' }}>
                  {item.title}
                </h3>

                <p className="perspective-critique">&ldquo;{item.critique}&rdquo;</p>

                <div className="blindspot-callout">
                  <div style={{ fontSize: '0.75rem', fontWeight: 700, color: '#c4b5fd', textTransform: 'uppercase', marginBottom: '0.2rem' }}>
                    Overlooked Angle
                  </div>
                  <div style={{ fontSize: '0.85rem', color: '#e2e8f0' }}>{item.keyBlindSpot}</div>
                </div>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* SECTION 7: Evidence vs Belief */}
      {(activeTab === 'all' || activeTab === 'evidence') && (
        <section id="sec-evidence" className="audit-section">
          <div className="section-header">
            <div className="section-title-wrap">
              <Zap className="section-icon" size={22} color="#f59e0b" />
              <div>
                <h2 className="section-title">Evidence vs. Belief Audit</h2>
                <p className="section-subtitle">
                  Separating verifiable empirical facts from subjective predictions and beliefs.
                </p>
              </div>
            </div>
            <span className="badge-tag">{result.evidenceVsBelief.length} Statements Deconstructed</span>
          </div>

          <div style={{ overflowX: 'auto' }}>
            <table className="evidence-matrix-table">
              <thead>
                <tr>
                  <th style={{ width: '38%' }}>User Statement / Claim</th>
                  <th style={{ width: '16%' }}>Epistemic Status</th>
                  <th style={{ width: '26%' }}>Diagnostic Classification</th>
                  <th style={{ width: '20%' }}>Cognitive Significance</th>
                </tr>
              </thead>
              <tbody>
                {result.evidenceVsBelief.map((item, idx) => (
                  <tr key={idx}>
                    <td>
                      <span style={{ fontStyle: 'italic', color: '#f1f5f9' }}>
                        &ldquo;{item.statement}&rdquo;
                      </span>
                    </td>
                    <td>
                      <span className={`epistemic-badge epistemic-${item.category}`}>
                        {item.category}
                      </span>
                    </td>
                    <td>{item.groundingStatus}</td>
                    <td>{item.whyItMatters}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>
      )}

      {/* SECTION 8: High Value Questions */}
      {(activeTab === 'all' || activeTab === 'questions') && (
        <section id="sec-questions" className="audit-section">
          <div className="section-header">
            <div className="section-title-wrap">
              <HelpCircle className="section-icon" size={22} color="#06b6d4" />
              <div>
                <h2 className="section-title">High-Value Questions Worth Investigating</h2>
                <p className="section-subtitle">
                  Targeted questions that meaningfully improve clarity before committing.
                </p>
              </div>
            </div>
            <span className="badge-tag">{result.questions.length} Probes</span>
          </div>

          <div className="questions-list">
            {result.questions.map((q, idx) => (
              <div key={idx} className="question-card">
                <div className="question-number-badge">{idx + 1}</div>
                <div className="question-content">
                  <div className="question-header">
                    <span className="question-text">{q.question}</span>
                    <span className="question-category-tag">{q.category}</span>
                  </div>
                  <div className="question-meta">{q.whyItMatters}</div>
                  {q.suggestedAction && (
                    <div className="action-chip">
                      <Sparkles size={12} />
                      <span>{q.suggestedAction}</span>
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* Bottom Actions Bar */}
      <div className="footer-reset-bar">
        <div>
          <div style={{ fontWeight: 600, color: '#f8fafc', fontSize: '1rem' }}>
            Ready to test another hypothesis or scenario?
          </div>
          <div style={{ color: 'var(--text-muted)', fontSize: '0.85rem' }}>
            BlindSpot does not store your decision data. All sessions are private.
          </div>
        </div>

        <div style={{ display: 'flex', gap: '0.75rem' }}>
          <button type="button" className="btn-secondary" onClick={handleCopyReport}>
            <Copy size={15} />
            <span>Copy Full Report</span>
          </button>
          <button
            type="button"
            className="btn-scan"
            onClick={onReset}
            style={{ padding: '0.65rem 1.5rem', fontSize: '0.95rem' }}
          >
            <RotateCcw size={16} />
            <span>Start Another Analysis</span>
          </button>
        </div>
      </div>
    </div>
  );
};
